### PR TITLE
Added some architectural images

### PR DESCRIPTION
**Pull request by alikureishy**

### CODE REVIEW

**Review by naveedhd — APPROVED** [review]

**Comment by naveedhd** [comment]
@safdark i think squashing the commits before merging would be good.

**Comment by naveedhd** [comment]
In my last PR, I have placed the image in (newly created) `docs` folder.. if we are keeping images in `img` folder, should move that also.

**Comment by alikureishy** [comment]
Done

**Comment by alikureishy** [comment]
Everything merged back to master.

Plz check.

**Pull request merged**
