### PR TITLE
Added missing import for enum34 to support 'from enum import Enum'

### PR DESCRIPTION
**Pull request by alikureishy**
I haven't yet been able to test this out, but I will when I have access to the ROS environment again. Meanwhile, you can take a look at the fix.

### CODE REVIEW

**Comment by alikureishy** [comment]
The issue was that the enum package referenced in the params.py file exists out-of-box in python 3.6+. Python 2.7 doesn't have that library out-of-box, so it had to be added explicitly, via the 'enum34' library. I’ve changed the requirements file to install this.

**Review by Verichev — APPROVED** [review]

**Comment by Verichev** [comment]
Hi, Ali, did you submitted the project again?

**Comment by alikureishy** [comment]
Hi Eugene,
Sorry I'm traveling and haven't had access to the GPU machine that I was
using for this project at home.
Yes, I resubmitted the project. I had missed the instruction to submit it
again, so I just did it in case it was holding up anyone's graduation. Did
you get the graduation email? And have you filled out the survey? It seems
that survey step is required in order to receive the certificate.
Ali

**Comment by alikureishy** [comment]
I will try out what you suggested as soon as I'm back home...

**Comment by alikureishy** [comment]
This was my 5th Nanodegree, so I've been needing a break for quite a long
time to recharge.

**Pull request merged**
